# Generated by Django 3.0.4 on 2020-03-18 20:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200318_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 20, 16, 9, 766555, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
